-- Config file generated by blmake!
-- All tables expect string values. Leave empty if unused.
-- `debugging` expects a boolean value.
-- Everything else expects a string value. Use "" if unused.

Build = {
    compiler = "g++",      -- e.g., "g++"
    files = {"main.cpp", "os.cpp", "utils.cpp"}, -- e.g., {"main.cpp", "utils.cpp"}
    lang_exts = {"-std=c++20"},     -- e.g., {"-std=c++20"}
    include_dirs = {"/opt/homebrew/include", "/opt/homebrew/Cellar/libarchive/3.7.9/include"},  -- Directories for include files (optional)
    linker_opts = {"/opt/homebrew/lib"},   -- Paths to check for included dependencies
    dependencies = {"archive", "zstd"},  -- Libraries to link against, e.g. {"lib1", "lib2"}
    preproc_opts = {},  -- Preprocessor options (e.g., macros, include paths)
    optimization = "-O0",  -- Optimization level (e.g., "-O2", "-Os")
    debugging = false,  -- A BOOLEAN value indicating whether to include debugging info ("-g")
    build_type = "",    -- e.g., "Debug" or "Release"
    output = "main",        -- e.g., "myprogram"
    src_dir = "src",       -- Source directory
    out_dir = "build",       -- Output directory
    hooks = {},         -- e.g., {pre_build = "scripts/pre_build.sh"} 
}

-- Customize behavior below!
-- For example:
--[[
if Full_build.build_type == "Debug" then
    Full_build.optimization = "-O0"
end
]]
